services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgres:MyBase#1270@db/dockert
    ports:
      - "8051:8051"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyBase#1270
      - POSTGRES_DB=dockert

volumes:
  postgres_data:
